name: CI

# Trigger on push and pull requests
on:
  push:
    branches: 
      - "**"   # all branches
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CI checks
        run: echo "Running CI checks..."
